--
--  Copyright (c) 2018, German Rivera
--  All rights reserved.
--
--  Redistribution and use in source and binary forms, with or without
--  modification, are permitted provided that the following conditions are met:
--
--  * Redistributions of source code must retain the above copyright notice,
--    this list of conditions and the following disclaimer.
--
--  * Redistributions in binary form must reproduce the above copyright notice,
--    this list of conditions and the following disclaimer in the documentation
--    and/or other materials provided with the distribution.
--
--  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
--  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
--  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
--  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
--  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
--  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
--  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
--  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
--  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
--  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
--  POSSIBILITY OF SUCH DAMAGE.
--

with Watchdog_Timer;
with Interfaces;
with System.Machine_Code;
with Memory_Utils;
with Microcontroller.Arch_Specific;
with Microcontroller.Clocks;
with Reset_Counter;
with Low_Level_Debug;

package body Startup is
   use Interfaces;
   use System.Machine_Code;

   procedure Enable_FPU;
   --
   --  Enable FPU hardware
   --

   ----------------
   -- Enable_FPU --
   ----------------

   procedure Enable_FPU is
      FPU_Control_Reg : Unsigned_32 with
        Address => System'To_Address (16#E000ED88#);
      Reg_Value : Unsigned_32;
   begin
      Reg_Value := FPU_Control_Reg;
      Reg_Value := Reg_Value or 16#F00000#;
      FPU_Control_Reg := Reg_Value;

      --  Wait for store to complete and reset pipeline with FPU enabled:
      Asm ("dsb" & ASCII.LF &
           "isb" & ASCII.LF,
           Clobber => "memory",
           Volatile => True);
   end Enable_FPU;

   -------------------
   -- Reset_Handler --
   -------------------

   procedure Reset_Handler is
      procedure Gnat_Generated_Main with
                 Import,
		 Convention => C,
		 External_Name => "main";
   begin
      --
      --  NOTE: Only "No_Elaboration_Code_All" packages can be invoked
      --  by this subprogram.
      --

      Microcontroller.Arch_Specific.Disable_Cpu_Interrupts;

      --
      --  Watchdog timer needs to initialized as soon as possible, to prevent
      --  it from firing, in case it is enabled by default:
      --
      Watchdog_Timer.Initialize;

      Low_Level_Debug.Initialize_Rgb_Led;
      Low_Level_Debug.Set_Rgb_Led(Red_On => True);

      Microcontroller.Clocks.Initialize;
      Low_Level_Debug.Set_Rgb_Led(Green_On => True);

      --
      --  In case C code is invoked from Ada, C global variables
      --  need to be initialized in RAM:
      --
      Memory_Utils.Copy_Data_Section;
      Memory_Utils.Clear_BSS_Section;

      Reset_Counter.Update;
      Enable_FPU;
      Low_Level_Debug.Initialize_Uart;
      Low_Level_Debug.Set_Rgb_Led; --  off

      Microcontroller.Arch_Specific.Interrupt_Handling_Init;
      Microcontroller.Arch_Specific.Enable_Cpu_Interrupts;

      --
      --  Call main() generated by gnat binder, which will do the elaboration
      --  of Ada library-level packages and then invoke the main Ada subprogram
      --
      --  NOTE: Before calling 'Gnat_Generated_Main' only
      --  "No_Elaboration_Code_All" packages can be invoked.
      --
      Gnat_Generated_Main;

      --
      --  We should not return here
      --
      pragma Assert (False);
   end Reset_Handler;

   ----------------------------------
   -- Unexpected_Interrupt_Handler --
   ----------------------------------

   procedure Unexpected_Interrupt_Handler is
   begin
      Low_Level_Debug.Print_String ("*** Unexpected Interrupt ");
      Low_Level_Debug.Print_Number_Decimal (
         Microcontroller.Arch_Specific.Get_IPSR_Register,
         End_Line => True);

      pragma Assert (False);
      loop
	 null;
      end loop;
   end Unexpected_Interrupt_Handler;

end Startup;
