/**
 * @file startup.c
 *
 * Startup code for RISCV32 processors
 *
 * @author: German Rivera
 */
#include "mem_utils.h"
#include <stdint.h>

extern void microcontroller__mcu_specific__pre_elaboration_init(void);
extern void main(void);

extern void reset_handler(void);

/**
 * Reset exception handler invoked from _start
 */
void reset_handler(void)
{
    extern uint32_t __data_load[];
    extern uint32_t __data_start[];
    extern uint32_t __data_end[];
    extern uint32_t __bss_start[];
    extern uint32_t __bss_end[];
    size_t size;

    /*
     * Copy initialized C global/static variables from flash to SRAM
     */
    size = (uintptr_t)__data_end - (uintptr_t)__data_start;
    memcpy(__data_start, __data_load, size);

    /*
     * Initialize uninitialized C global/static variables to 0s:
     */
    size = (uintptr_t)__bss_end - (uintptr_t)__bss_start;
    memset(__bss_start, 0, size);

    /*
     * NOTE: C global and static variables can only be accessed after this point
     */

  	/* Enable FPU */
#if 0 //???
	li t0, MSTATUS_FS
	csrs mstatus, t0
	csrr t1, mstatus
	and t1, t1, t0
	beqz t1, 1f
	fssr zero
1:
#endif

    microcontroller__mcu_specific__pre_elaboration_init();

    /*
     * Invoke the main() function generated by the gnat binder:
     */
    main();

    /*
     * We should never return here:
     */

    /*
     * Trap CPU in a dummy infinite loop:
     */
    for ( ; ; )
        ;
}

