/* Configuration for frdm_kl25z_autonomous_car generated by Alire */
#ifndef FRDM_KL25Z_AUTONOMOUS_CAR_CONFIG_H
#define FRDM_KL25Z_AUTONOMOUS_CAR_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "frdm_kl25z_autonomous_car"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
